### ISSUE TITLE
Starter sites

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#10]
**Main goal**
Create the first batch of 20 demos for Hestia ( same 20 for Neve ) in Elementor in the next 3 months. We'll try to see the impact it has on our users and based on that, we can go on with other batch.

**UPDATE:** Until we have Neve PRO released, we want to focus just on Neve/Neve PRO, so we'll have the starter sites just for Neve for the moment.

**Things to consider**
- Regarding **images**, we first need to change the importer to allow us to replace specific images with placeholders ( this will be done in https://github.com/Codeinwp/ti-onboarding/issues/5 ).
So, we'll have a parameter or other way of importing only the images we are sure are GPL ( to be safe, we should import just mystock photos ). For the demo itself, we can use any GPL images ( pixabey etc )

- For big header images, if there isn't any other way, we can also try making some pictures by ourselves, but we shouldn't remain stuck because of this.

- We should have 9 of the simplest demos in the lite versions and the rest of them in the pro versions

- We should make sure the sites are really **starter sites**.  Meaning that we should pay more attention and decide on specific and real sections/elements that can be used in that specific case so that the end user need to just update some texts in order (and don't remove any section) to have his site up in minutes.
For each specific case, investigate some more advanced integration, with different plugins that would make sense to be used for each case.
As a specific example, we have this one https://demo.themeisle.com/neve-vet-center/ compared to https://avada.theme-fusion.com/veterinarian/.
For me, the Avada one, is more focused on the domain, in that case, veterinarian. All those sections make sense and are useful for a user that would want to build a site for a veterinarian (and with more focused text), like: a Hero area, About section + contact details, testimonials, CTA, services, and contact. And all the text is pretty much focused on things that would make sense for a veterinarian.
In our case, there are many things that don't make sense for such a site, and most likely would need to be changed by the user, before he would be able to publish his site. For example, the icons https://prnt.sc/lxyz2r , the main title and especially the subtitle doesn't make any sense and would definitely need to be changed, and more of the text on the demo.
Another good example I see this one https://avada.theme-fusion.com/wedding/. I imagined building a wedding site, and all the sections I would need are there already, with text so well written, that only the key elements ( specific to each user would need to be changed to have your site up and running really fast, like: name of the bride and groom, date and location of the wedding, and other personal details )

- We will most probably deprecate most of the old themes, and replaced them in all the listings with the starter sites.

**Steps**
1. Review ( & update ) existing demos to make sure they can be used as truly simple to use starter sites.
2. Recreate all the demos that are already created in Hestia & Neve in the other theme. ( the ones that use Hestia sections can be recreated in Elementor, as close as possible. Don't need to be identical. And do this, only if it makes sense ).
3. Move the most interesting frontpages templates in OBFX as templates. ( the PRO templates, can be added somewhere on git, until we know what happens with OBFX pro or sizzify )
4. Create new demos.

**Few Ideas for demos** (with examples of plugins that can be integrated):
- fashion/style blogger ( social sharing, Instagram feed, Disqus, plugins that allow you to add adds to the site )
- wedding ( plugin de RSVP, gift registry, countdown )
- photography ( event schedule, slider, optimization, Pinterest pin it button )
- traveler blog
- agency
- traditional blog
- personal portfolio
- product showcase
- magazine
- recipes
- real estate (Essential Real Estate plugin)
- construction
- as a PRO demo: have a starter site similar to themeisle.com, a shop with EDD, Paypal etc, woocommerce

**Comment by rodica-andronache** [comment]
@radu-themeisle for Neve ( the free version ) we could have only 2 new starter sites, for WooCommerce and Travel Blog. You can start thinking of a structure for these.

**Comment by radu-themeisle** [comment]
I finished going over [Neve Vet Center](https://demo.themeisle.com/neve-vet-center/) and made changes to it. Your feedback is welcomed 🙂

cc: @stefan-cotitosu

**Comment by rodica-andronache** [comment]
@radu-themeisle looks very good for me 👍 the only things I would change, is the menu item, call it Home, and add a slight opacity over the top image, to make sure the text ( white ) is visible on other images too.
For the other demos that you want to improve, I suggest you maybe do it as an internal page at the beginning ( not the frontpage ) as until we update the theme with the changed files, I guess the users will see the new preview, but import the old one.
For this starter site, we could do an update today

**Comment by rodica-andronache** [comment]
and maybe here, either have some space between the boxes, or make sure the shadow is not so weird between them https://prnt.sc/m71n3l

**Comment by radu-themeisle** [comment]
I implemented your feedback, the top image already had a black overlay I was afraid too much opacity would make the image hard to see because it has a lot of dark colors, but it looks good.

I'll keep in mind for the rest of the demos to work on a separate page.

**Comment by stefan-cotitosu** [comment]
@radu-themeisle Looks nice. I think it's definitely better than the old one 👍 

- I would change this text here, to be left aligned, or move the Contact Info content to the center of the column.
Something here is not perfect 😄 
![neve-vet-contact](https://user-images.githubusercontent.com/26867648/51167163-7c484d00-18ae-11e9-9c3e-9399a288d285.png)

- Maybe we can have only 2 boxes per row on tablet view for the "Why choose Neve Vet Center" section.
![neve-why-vet](https://user-images.githubusercontent.com/26867648/51167233-b31e6300-18ae-11e9-967d-ade939d08227.png)

- The top bar looks a little bit weird on mobile, because of the icon being on a different row than the menu item. Not sure which is the best solution here. Maybe to use CSS to have the menu item and the content on different rows?
![neve-mobile](https://user-images.githubusercontent.com/26867648/51167917-7c494c80-18b0-11e9-85de-17a38428a685.png)

**Comment by radu-themeisle** [comment]
@stefan-cotitosu thank you for the feedback you have some good points there 😊
I aligned the Contact section to the left, seems to make sense and I've seen other templates doing the same (keeping the alignment the same across devices).
And implemented the rest of your feedback for tablet and mobile.

**Comment by radu-themeisle** [comment]
[Neve Energy](https://demo.themeisle.com/neve-energy-panels/new-neve-energy/) is finished. I await your feedback: @rodica-andronache & @stefan-cotitosu
I was thinking to rename it to Neve Power or strip "panels" from the name and slug. The current one wouldn't do justice to the new design.

**Comment by rodica-andronache** [comment]
@radu-themeisle I wouldn't change the slug, as it might be used in some articles ( promotions ) but the title, sure, can be changed.
What I would do:
- add an overlay over the hero section image, so the text can be more visible with other images too
- for all buttons - on hover, make the border blue ( the color you are using )
- for the Updates & Advice section, I think there are too many buttons ( plus, without spacing ). I would make those simple links
- the Apply button could point to the Contact section

I leave this here too, you can work on it when you have some time, please - there are small things that could be improved, you can do your magic :)
https://demo.themeisle.com/neve-zelle/

**Comment by rodica-andronache** [comment]
I'm leaving this here too, even though is not related to the starter sites directly, but I think you can also help :) The Zelle template we have in Neve and Hestia ( the import that also gets your content, if you came from Zelle ). If you add a bit more text, it gets out of the container https://prnt.sc/ma046j

**Comment by stefan-cotitosu** [comment]
@radu-themeisle Looks good 👍 Below are my suggestions.

- The main title should be on just one row, there are just 3 words and it looks weird now
- Change the site tagline. "Energy for everyone" is better than "Just another site...." It gives me the feeling that we are bored by our products :) 
- Make the buttons border blue on hover. It looks like the button is disappearing when you want to click on it.
- Add a dark overlay on all images. The site background is white and any image make too much contrast.
- align the following text to left on mobile. If it's not a section title, for me it's hard to read on mobile, as each row starts from a different distance.

![neve-energy-demo-1](https://user-images.githubusercontent.com/26867648/51523627-c8f2d180-1e34-11e9-9dc0-d7cfc460933b.png)

![neve-energy-demo](https://user-images.githubusercontent.com/26867648/51523630-cbedc200-1e34-11e9-857d-3f5f4d9ff977.png)

**Comment by rodica-andronache** [comment]
@radu-themeisle will leave this here too for when you get a chance to see the Lawyers demo too, make sure we don't use copied articles as we have here on the blog, as we could get in trouble for that. We need to replace them https://demo.themeisle.com/neve-lawyers/neve-lawyers-demo-blog/

**Comment by rodica-andronache** [comment]
@radu-themeisle like Ionut mentioned on Slack it would be a good idea to reuse some of the design elements in the retired themes ( Parallax, Lllorix, Lawyeria etc ) for the starter sites 👍

**Comment by radu-themeisle** [comment]
- [ ] parallax
- [ ] one
- [ ] naturelle
- [ ] maybe bookrev, lawyeriax

**Comment by radu-themeisle** [comment]
I finished the "transforming" the [Zelle Demo](https://demo.themeisle.com/neve-zelle/new-zelle-demo/).
Some things that I'll do once we make the switch to this one:
1. Change the name of the menu items. They will continue to link inside the page, but will have different names.
2. On the Blog it will show only the "Tips" category.

Let me know what you think and if you spot anything wrong or think something could be improved.

Thank you!

**Comment by radu-themeisle** [comment]
I finished the demo with Woocommerce, [Neve Music World](https://demo.themeisle.com/neve-woocommerce).
You feedback is appreciated! 🙂

**Comment by rodica-andronache** [comment]
@radu-themeisle let me know when you have ready the PR with the demos you've added last week so we can add them in Neve :) We can check today at the meeting with the boys, how the pro demos can be added in Neve PRO.

You can also add the Zelle demo there. Before, is there something that can be done for these images https://prnt.sc/mswrl2 ? And on the blog page, some images are smaller than others, some posts have content, some no, maybe you can check that? https://prnt.sc/mswryy 

After that, can you please try and see if it possible to recreate the Shop Isle demo in a starter site, as mentioned here https://github.com/Codeinwp/neve/issues/379 ? Thanks
