### ISSUE TITLE
Options to remove the onboarding

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#13]
We should have some options in the code that would easily allow users to remove the onboarding notice, and the sites library if necessary. ( this can be used for example by hosting companies that want to offer their own onboarding )

**Comment by abaicus** [comment]
@rodica-andronache The notice is already removable by filtering the about page config (`ti_about_config_filter` filter). 

I've added a filter for disabling the whole module `ti_onboarding_filter_module_status`.

**Comment by abaicus** [comment]
@rodica-andronache I've done it in a simpler form. Just have to define a constant: 

`define( 'TI_ONBOARDING_DISABLED', true );`
