### ISSUE TITLE
remove json content type on api request 

### ISSUE THREAD

**Issue by selul** [Codeinwp/ti-onboarding#19]
@abaicus on some environment, the JSON conten type might be blocked due to various server configurations, throwing an error when the import occurs. 

It's better to use `emulateJson` in the Vue HTTP handler, you can see an example here -> https://github.com/Codeinwp/optimole-wp/blob/master/assets/vue/store/actions.js#L20-L21  which should solve the issue

**Comment by abaicus** [comment]
body{font-family:Helvetica,Arial;font-size:13px}@selul, thanks for the pointer! I'll make sure to fix this.   On 28 January 2019 at 15:53:29, Marius Cristea (notifications@github.com) wrote: emulateJson in the Vue HTTP handler
