### ISSUE TITLE
get in touch should open in a new tab

### ISSUE THREAD

**Issue by selul** [Codeinwp/ti-onboarding#20]
@abaicus I really like the error reporting you did when importing a site, congrats 💃 . 

One small thing which I think is frustrating for some users is when they open the get in touch link, they get redirected, instead of opening the link in a new tab  -> http://prntscr.com/md9qo5

Some of them might not know what get in touch do and forget to copy the error log. Due to this, they are not able to come back and copy the error.

**Comment by abaicus** [comment]
body{font-family:Helvetica,Arial;font-size:13px}One issue we have with this is that the TRT doesn't allow us to use _blank targeted links. That's why it isn't opened in a new tab. I would like to do so, but I'm not sure what they'll say. :(cc: @rodica-andronache   On 28 January 2019 at 16:03:47, Marius Cristea (notifications@github.com) wrote: Some of them might not know what get in touch do and forget to copy the error log. Due to this, they are not able to come back and copy the error.

**Comment by rodica-andronache** [comment]
not sure if it would be better, but we could move the copy button before the message?

**Comment by selul** [comment]
ah, ok, you can ignore this then.
Or you can change the copy behaviour in something like copy&get in touch which, on click, should copy and redirect to that page. 

Don't know if this is better, is not such important.

**Comment by selul** [comment]
one more thing here, you can add this icon near that external link which could better inform user that he will be redirected -> 
![image](https://user-images.githubusercontent.com/3330746/51842130-df0eff00-2318-11e9-8201-78fea9a10ea5.png)

**Comment by rodica-andronache** [comment]
we could add that icon in css so we don't affect the string

**Comment by rodica-andronache** [comment]
ah, I think I didn't understand this. I had the impression that the icon would suggest it would open the link in the same window, but it's the other way around. Adding _blank wouldn't be nice for accessibility. Don't have another idea, then leaving it the same. what do you think?

**Comment by selul** [comment]
@abaicus i would get rid of blank, keep it like this but just add the icon for external link

**Comment by abaicus** [comment]
@rodica-andronache No, it would suggest it's an external link that should be opened in a new window, I think. 💃

**Comment by rodica-andronache** [comment]
ok, yes, makes sense 💃
