### ISSUE TITLE
List Neve/Hestia's starter sites on themeisle

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#21]
We want to list Neve & Hestia's starter sites as separate themes on Themeisle/JFT to make use of more specific categories. Also, on activation, in the onboarding, we would give the corresponding starter site as the default one.
@selul maybe you could help with ideas on how we could do this technically 👍

**Comment by ineagu** [comment]
if on-boarding auto-starts I think is good enough for me

**Comment by selul** [comment]
@rodica-andronache this is tricky but I think we can find a good solution and easy to implement but we will need a bit of tweaking the onboarding library. 

It will have two parts: 
1. ON jft each starter site will be a different zip file containing the setup for a specific starter site. 
2.  ti onboarding tweak:
    - On the ti-onboarding, we need to set up an auto-install option, which could use a custom constant, i.e `TI_ONBOARDING_ACTIVE_SITE`  which could be one of the site slugs. 
    - This can be defined on the theme that uses the onboarding and wants a specific site installed by default. 
    - When the ti-onboarding finds this particular constant defined, will prompt a notice to the user, i.e WE will start installign the Neve Vet site, please confirm. Once that he will confirm this, the importing will occur. This notice will come up as soon as the user installs the theme. 

At the end we will have X variations of neve, each one containing one definition of that TI_ONBOARDING_ACTIVE_SITE for each demo. 

I can talk with andrei or whoever would like to tweak this further details.

**Comment by ineagu** [comment]
I have mixed feelings about the solution @selul in a way that the user next time when he would install Neve for e.g from w.org would expect same behaviour and might get confused.

Having a clear on-boarding that is easy to start or auto-start, which maybe at best, can show the prefered theme first might provide a more consistent experience for everybody. Same if somebody makes a video/documentation etc.

**Comment by rodica-andronache** [comment]
I find it better too, to just show that demo as the prefered one

**Comment by selul** [comment]
Fair enough. I think on install we can just redirect to the selected site popup. Which demo to show could be configured either from the altered version of the theme, or a child theme ?

**Comment by selul** [comment]
Ideally keeping the configuration for which demo to start in a child theme is better, avoiding to create multiple versions of the main theme.

**Comment by abaicus** [comment]
@ineagu I wanted to ask how / if we're going to list the same demo twice if it's available in Gutenberg & in Elementor. If so, how do you think it would be better to handle this. 

cc @rodica-andronache

**Comment by ineagu** [comment]
ideally we won't list it twice on the user side.

if elementor is installed we list elementor based starter sites by default, if elementor is not present and gutenberg is, we list those.

the 2nd option probably is good to be available as an advanced setting under the starter sites tab in options, something like : "view gutenberg based starter sites "

**Comment by abaicus** [comment]
Right now we have tabs (that are hidden by default because we don't have any gutenberg demos yet) for showing demos for different page builders. I'm guessing we could switch the order of those and what is selected by default on the end user's site.  

But my actual question was more regarding the listing on the TI/JFT websites, not on the user's end.

**Comment by ineagu** [comment]
ah ok, we would list elementor ones for now for e.g and in 1 year or so gutenberg ones, still they would probably be almost identical and when users would install they can pick.

**Comment by abaicus** [comment]
@rodica-andronache This should work as expected now. It shows the featured demo at the top if you use one of the child themes (from [here](https://github.com/Codeinwp/neve-children) or have the `TI_ONBOARDING_ACTIVE_SITE` constant defined as one of the demo's slug.

**Comment by abaicus** [comment]
@rodica-andronache One suggestion - should we maybe change the button text here to say something else so the user doesn't assume wrongly that the niche content is alredy bundled in the theme? 

![image](https://user-images.githubusercontent.com/15010186/52524722-edf69980-2ca8-11e9-883c-f7ffb8c896ce.png)

**Comment by rodica-andronache** [comment]
yes, do you have something in mind for that?

**Comment by selul** [comment]
@rodica-andronache @abaicus  the implementation of the auto-start seems kind of incomplete i guess 

Basically, the only difference between having neve with a favourite site and neve simple is that the favourite site is prioritized on top of the list -> http://prntscr.com/mjkaub  or http://prntscr.com/mjkbc4 

I think that's fine but for a neve newbie or someone who is not familiar with neve will be kind of confusing. 

I would do the next things: 

1) change the notice for neve with fav site with something more targeted. i.e like Andrei said, instead of try one of our etc, something like `Start setup of Neve charity`
2) change the `ready to use ` to `almost ready to use`

**Comment by selul** [comment]
We have now a workflow in place. let's followup if there are any issues with it.
