### ISSUE TITLE
[Hestia] Importing Original Starter Site without WooCommerce fails

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#211]
When trying to import the `Original` or the `WooCommerce` Starter Sites in Hestia, `without WooCommerce` fails all the time. 

![download (3)](https://user-images.githubusercontent.com/3266155/77293158-70de8600-6cea-11ea-8efc-16937c4f602e.png)

![download (4)](https://user-images.githubusercontent.com/3266155/77293170-7b991b00-6cea-11ea-88c3-aae5ab728d98.png)

![download (5)](https://user-images.githubusercontent.com/3266155/77293185-82c02900-6cea-11ea-8373-58b960007fef.png)

The log file: 
[ti_theme_onboarding.log.txt](https://github.com/Codeinwp/ti-onboarding/files/4367848/ti_theme_onboarding.log.txt)

**Comment by irinelenache** [comment]
@rodica-andronache tested it and the issue is not happening anymore now 👍
