### ISSUE TITLE
improve unit tests compatibility 

### ISSUE THREAD

**Issue by selul** [Codeinwp/ti-onboarding#24]
@abaicus  Now the importing actions are almost impossible to cover using unit tests. We should avoid functions like `wp_send_json_success`, `wp_send_json_error` and use WP_REST_Response as returns in the  custom rest routes we have developed. The former ones stop the code execution after they are called, preventing any unit test to fulfil. 

I've tried to move the theme_mods under this pattern but we should do this for every rest callback. 

Subsequently, after we have this ready, we can build unit tests for each callback, similar to the theme mods importer.

**Comment by abaicus** [comment]
Fixed this 👍
