### ISSUE TITLE
Remove guideline text from the starter site

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#29]
@radu-themeisle I think we've talked about this before, let's remove these texts from the starter site, and not add that in the future. We can have those details mentioned in the documentation 👍 Thanks
https://prnt.sc/mjfmx2

**Comment by radu-themeisle** [comment]
Ok, I can remove them once they are in the documentation.
Maybe @SilviuDinu can help put them into the doc?
