### ISSUE TITLE
Onboarding tweaks

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#51]
@abaicus what we've talked in the morning.
The demo is this one https://demo.themeisle.com/neve-shop/
And the plugin used for the slider is https://wordpress.org/plugins/maxslider/

We should think of the best way of doing this, either importing the options for this specific plugin or creating a slider widget in OBFX or any other idea

**Comment by rodica-andronache** [comment]
@abaicus after you finish things with the header components, you can go on with some updates for the onboarding, as we've talked, so we can go on with the starter sites redesigns 🥇 .
-> update the demo exported to also export options
-> mention the unsplash links in the notice message https://github.com/Codeinwp/ti-onboarding/issues/32

**Comment by abaicus** [comment]
@rodica I've checked the slider part and the current plugin generates a CPT and on import it doesn't really seem to import properly. I think it's a bit messy to try importing this. Maybe rather add an elementor widget in TI companion. Or move this to pro and add the widget in elementor booster? If that's in the base pack.

**Comment by rodica** [comment]
Wrong @rodica I'm afraid. Looks like you want *rodica-andronache
<https://github.com/rodica-andronache>*

**Comment by rodica-andronache** [comment]
@abaicus ok, as we've talked, I agree we can move this as Elementor widget. I've moved it here https://github.com/Codeinwp/themeisle-companion/issues/355

Is this thing possible: remove the extra spacing in the about page #40 ?

**Comment by rodica-andronache** [comment]
another small thing, on my mac I see this https://prnt.sc/nmb7je

**Comment by abaicus** [comment]
> another small thing, on my mac I see this https://prnt.sc/nmb7je

This seems to have been handled by somebody at some point... not really sure where :)) Might've been a composer dep that wasn't the latest version?
