### ISSUE TITLE
Remove xml files from wporg themes

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#59]
As far as I understand from here https://make.wordpress.org/themes/2019/06/12/meeting-notes-from-the-11th-of-june-2019/ it was decided that xml files are not allowed in the theme, so we should have the same import mechanism for the free starter sites as we do for the pro ones.

**Comment by ineagu** [comment]
@rodica-andronache what they say I believe is not importing it, but rather having a "link" to the xml, let's wait a bit and clarify what's the goal and what's the best approach

**Comment by rodica-andronache** [comment]
yes, just noted this so we can follow it
