### ISSUE TITLE
Zelle Import throws fatal error without Elementor preinstalled

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/ti-onboarding#6]
If you try running the migration without Elementor pre-installed, the request throws a fatal error as it doesn't install Elementor. 

We should make sure the migration process checks if Elementor was installed, install it and activate it if it isn't, and then run the migration process. 

cc: @cristian-ungureanu

**Comment by cristian-ungureanu** [comment]
@abaicus, @rodica-andronache I manage to fix this but I think it's more complex than that.

I think that now if we install plugins when the user makes the import, we should also let them know so we'll need that pop-up where we tell them what plugins are installed http://prntscr.com/m2lp32 (without the general part)

Also, giving the user the option to disable Elementor will generate the same issue for every template as we have now for Zelle import. My idea is to separate plugins to required (plugins that will appear in plugins list but can't be deactivated) and mandatory (plugins that can be deactivated by the user). For this, we'll need to change the exporter a bit.

Another way is to add a field 'required plugins' in theme config for each template but I find this not optimal as we plan to have many demos.

The last thing I can think of is to have a list of mandatory plugins stored in onboarding and check if the template requires one of them. If it does, we won't display the toggle to deactivate it.

What do you think?

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I guess, to make this as generic as possible we could have the pop-up for Zelle the same as for the other demos, including the general part (but without the options that don't make sense there), where we can have an extra option/toggle for "Theme mods from Zelle (your previous theme)" let's say for example ( that can be enabled/disabled by the user/or from the code )
Having this would allow us to also have the Zelle template available ( like all the other demos ) for users that didn't have Zelle before.

So, what I'm thinking is that all this should be adapted for all demos. All demos should be able to be configured to import also theme mods from a theme if that's the case ( for example, we could add something similar for Amadeus or Oblique at some point, to get the users to Neve ), and what you mentioned with some required/recommended plugins.

What you could do, is, based on the code, think about a structure for how you think we can configure this, in the exporter and in theme. But we would need something more concrete so we can decide if it makes sense or not. With that structure in mind, @abaicus should be able to help out with more ideas 👍

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , the feedback from @abaicus was useful but he fixed all those stuff.

I think we can close this issue and maybe open another one for adding Zelle starter site back and to add the images in the readme file.

All the other issues were resolved by @abaicus . 

Sorry for those commits, sometimes my brain fails.
