### ISSUE TITLE
Wrong onboarding links for child themes

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#60]
The `Try one of our ready to use Starter Sites` and `or go to the theme settings` links point to the wrong in place when a child theme is used. Tested in Neve  
![onboarding-links](https://user-images.githubusercontent.com/3266155/59690426-17d94300-91ea-11e9-9f79-53a96014d5de.png)

**Comment by cristian-ungureanu** [comment]
Fixed here https://github.com/Codeinwp/neve/pull/616 , the issue was from neve

**Comment by rodica-andronache** [comment]
@cristian-ungureanu as the mechanism is the same, we should fix this in Hestia as well 👍 . And check Zelle and Shop Isle as well ( don't remember if we have notices there as well )

**Comment by cristian-ungureanu** [comment]
@rodica-andronache 
For Zelle Pro there's no need to update the links, everything works
For Shopisle Pro https://github.com/Codeinwp/shop-isle-pro/pull/448
For Hestia / Hestia Pro https://github.com/Codeinwp/hestia-pro/pull/2098
