### ISSUE TITLE
Add a closing x button to the onboarding popup

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#61]
To make it more clear that you can skip this step, without any change
![onboarding-popip](https://user-images.githubusercontent.com/3266155/59691929-91723080-91ec-11e9-9d32-3e23d4695467.png)

**Comment by rodica-andronache** [comment]
+ Add a loading icon until the popup appears ( On slow internet connections, it's not very intuitive that something's happening )

**Comment by cristian-ungureanu** [comment]
@rodica-andronache the loading icon was added here https://github.com/Codeinwp/ti-about-page/pull/29 and the x button here https://github.com/Codeinwp/ti-onboarding/pull/65
