### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#68]
- update copyright message in onboarding
- add images in unsplash collections
- Hestia: https://github.com/Codeinwp/hestia-pro/issues/2100 - notice: 1 link to import default Hestia | 1 link to customizer

**Comment by abaicus** [comment]
@rodica-andronache I've added import on access. The thing that should be done is adding a parameter to the link for example: 

```
http://localhost:8080/wp-admin/themes.php?page=neve-welcome&readyimport=neve-main#sites_library
```

You have to specify the `readyimport=neve-main` argument.
