### ISSUE TITLE
After template is imported, redirect the user to the page edited in Elementor

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/ti-onboarding#7]
Like mentioned here, to have it as a temporary fix, until we have the Gutenberg demos https://github.com/Codeinwp/neve/issues/259

@cristian-ungureanu @abaicus we would need this these days. One of you, who feel you could do this in time, please let me know, and you can dedicate some time for this 👍

**Comment by rodica-andronache** [comment]
I'm ok with the extra button, maybe just name it 'Add your own content' or something similar, and have just one primary button, this one, as right now, I wouldn't know where to click from the three buttons.
And make the Back to Sites Library button just a link instead of a button, and move it to the left side.

Can we also have a tab with all the demos, no matter their types?

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , yes, I can add another tab but I'll need to change the code a bit. If you think that we'll need to mix them, a demo from elementor, then one from gutenberg, instead of grouping them by the editor, every array with a demo will have another parameter with its editor.

**Comment by rodica-andronache** [comment]
I was thinking that it would be good to be sure it's built in such a way that would allow the sites library ( when we want to do this ) to also have an All tab and a search box https://prnt.sc/lxc947
