### ISSUE TITLE
remove cypress related data in the exported library

### ISSUE THREAD

**Issue by selul** [Codeinwp/ti-onboarding#74]
we should add the cypress related files, i.e cypress.json and cypress folder into the [.gitattributes](https://github.com/Codeinwp/ti-onboarding/blob/master/.gitattributes) .

When you install a composer library, that file acts as a distignore list. 

You can read more details about that file's purpose here

https://madewithlove.be/gitattributes/

**Comment by cristian-ungureanu** [comment]
@selul the files are already there https://github.com/Codeinwp/ti-onboarding/blob/master/.gitattributes#L18-L21

**Comment by selul** [comment]
great.
