### ISSUE TITLE
Importing a demo after another one fail in Neve

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/ti-onboarding#9]
Using Neve, importing a second demo fail in some cases. By fail I mean that the front page of the second imported demo is not set as the site front page. Because of that, the new redirect open the wrong page when you click 'Add your own content'.

I will describe the steps to replicate this.

1. Import a Demo, any demo.
2. Import another demo. If it's Neve 2018, Vet Center or Energy Panels, the front page is correctly set. Importing another demo will just bring the files, posts, pages. The front page remains the one from the previous imported demo.

This seems to happen only in Neve. Hestia works fine.

**Comment by abaicus** [comment]
@stefan-cotitosu This was probably because of the front page slugs, or other stuff that might be fix after the refactoring. Would you please take another look at it? 

cc @rodica-andronache

**Comment by rodica-andronache** [comment]
seems ok now
